// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayoffEngine;

#nullable disable

namespace PayoffEngine.Data.Migrations
{
    [DbContext(typeof(PayoffEngineDbContext))]
    partial class PayoffEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PayoffEngine.PricingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Barrier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BarrierBreached")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CouponPaid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CouponRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Notional")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PricedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Redemption")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Strike")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PricingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
